<Project Sdk="Microsoft.NET.Sdk">

  <!-- dotnet publish -f net6.0 -o publish -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>netcoreapp3.1;net6.0</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
    <DebugType>embedded</DebugType>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <UseCurrentRuntimeIdentifier>true</UseCurrentRuntimeIdentifier>
    <!-- TODO test both IncludeAllContentForSelfExtract = true/false --> 
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Microsoft.Extensions.DependencyModel.csproj" />
  </ItemGroup>

</Project>
